// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/**
 * @title PhotonAttestationConsumer
 * @dev A Chainlink Functions consumer contract that requests and stores
 * verified smart contract security attestations generated by Photon.
 */
contract PhotonAttestationConsumer {
    struct Attestation {
        bool isScanned;
        uint8 riskScore;
        uint64 timestamp;
        bytes32 requestId;
    }

    // Mapping of scanned contract addresses to their security attestation
    mapping(address => Attestation) public attestations;

    // Mapping of active request IDs to the target contract address
    mapping(bytes32 => address) public activeRequests;

    // Chainlink Functions details (configured for the target network)
    address public immutable router;
    bytes32 public donId;
    uint64 public subscriptionId;
    uint32 public callbackGasLimit;

    // Events
    event AttestationRequested(bytes32 indexed requestId, address indexed targetContract);
    event AttestationUpdated(address indexed targetContract, bool isScanned, uint8 riskScore, uint64 timestamp);
    event RequestFailed(bytes32 indexed requestId, bytes err);

    // Errors
    error OnlyRouterCanFulfill();
    error RequestNotFound();

    constructor(address _router, bytes32 _donId, uint64 _subscriptionId, uint32 _callbackGasLimit) {
        router = _router;
        donId = _donId;
        subscriptionId = _subscriptionId;
        callbackGasLimit = _callbackGasLimit;
    }

    /**
     * @notice Simulates sending a request to the Chainlink Functions Router.
     * @param source The Javascript source code to execute.
     * @param targetContract The smart contract address to check.
     */
    function requestAttestation(string calldata source, address targetContract) external returns (bytes32) {
        // Generate a pseudo-random request ID for tracking/simulation
        bytes32 requestId = keccak256(abi.encodePacked(msg.sender, targetContract, block.timestamp));
        
        activeRequests[requestId] = targetContract;
        
        emit AttestationRequested(requestId, targetContract);
        return requestId;
    }

    /**
     * @notice Callback function called by the Chainlink Functions Router to fulfill requests.
     * @param requestId The request ID being fulfilled.
     * @param response The response payload containing the decoded data.
     * @param err Any error returned by the execution.
     */
    function handleOracleFulfillment(
        bytes32 requestId,
        bytes memory response,
        bytes memory err
    ) external {
        if (msg.sender != router) {
            revert OnlyRouterCanFulfill();
        }

        address targetContract = activeRequests[requestId];
        if (targetContract == address(0)) {
            revert RequestNotFound();
        }

        delete activeRequests[requestId];

        if (err.length > 0) {
            emit RequestFailed(requestId, err);
            return;
        }

        // Decode response: riskScore (uint8), isScanned (bool)
        if (response.length >= 32) {
            (uint8 riskScore, bool isScanned) = abi.decode(response, (uint8, bool));
            
            attestations[targetContract] = Attestation({
                isScanned: isScanned,
                riskScore: riskScore,
                timestamp: uint64(block.timestamp),
                requestId: requestId
            });

            emit AttestationUpdated(targetContract, isScanned, riskScore, uint64(block.timestamp));
        } else {
            emit RequestFailed(requestId, "Invalid response length");
        }
    }

    /**
     * @notice Utility view function for protocols to check if a contract is safe.
     * @param targetContract The address of the contract to check.
     * @return isScanned Whether the contract has been scanned by Photon.
     * @return riskScore The risk score (0-100, where 0 is safest).
     */
    function getSecurityStatus(address targetContract) external view returns (bool isScanned, uint8 riskScore) {
        Attestation memory att = attestations[targetContract];
        return (att.isScanned, att.riskScore);
    }
}
